// Generated by gencpp from file fusion/BBoxRequest.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_BBOXREQUEST_H
#define FUSION_MESSAGE_BBOXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fusion
{
template <class ContainerAllocator>
struct BBoxRequest_
{
  typedef BBoxRequest_<ContainerAllocator> Type;

  BBoxRequest_()
    : target()  {
    }
  BBoxRequest_(const ContainerAllocator& _alloc)
    : target(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::fusion::BBoxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fusion::BBoxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BBoxRequest_

typedef ::fusion::BBoxRequest_<std::allocator<void> > BBoxRequest;

typedef boost::shared_ptr< ::fusion::BBoxRequest > BBoxRequestPtr;
typedef boost::shared_ptr< ::fusion::BBoxRequest const> BBoxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fusion::BBoxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fusion::BBoxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fusion::BBoxRequest_<ContainerAllocator1> & lhs, const ::fusion::BBoxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fusion::BBoxRequest_<ContainerAllocator1> & lhs, const ::fusion::BBoxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fusion::BBoxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fusion::BBoxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::BBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::BBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::BBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::BBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fusion::BBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10e5cb524446adda5ea1765c6838590d";
  }

  static const char* value(const ::fusion::BBoxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10e5cb524446addaULL;
  static const uint64_t static_value2 = 0x5ea1765c6838590dULL;
};

template<class ContainerAllocator>
struct DataType< ::fusion::BBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fusion/BBoxRequest";
  }

  static const char* value(const ::fusion::BBoxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fusion::BBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target\n"
;
  }

  static const char* value(const ::fusion::BBoxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fusion::BBoxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBoxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fusion::BBoxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fusion::BBoxRequest_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSION_MESSAGE_BBOXREQUEST_H
