// Generated by gencpp from file fusion/BBox.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_BBOX_H
#define FUSION_MESSAGE_BBOX_H

#include <ros/service_traits.h>


#include <fusion/BBoxRequest.h>
#include <fusion/BBoxResponse.h>


namespace fusion
{

struct BBox
{

typedef BBoxRequest Request;
typedef BBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BBox
} // namespace fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fusion::BBox > {
  static const char* value()
  {
    return "1e9faa71b48d0be4f78c3d6eb8e3ba62";
  }

  static const char* value(const ::fusion::BBox&) { return value(); }
};

template<>
struct DataType< ::fusion::BBox > {
  static const char* value()
  {
    return "fusion/BBox";
  }

  static const char* value(const ::fusion::BBox&) { return value(); }
};


// service_traits::MD5Sum< ::fusion::BBoxRequest> should match
// service_traits::MD5Sum< ::fusion::BBox >
template<>
struct MD5Sum< ::fusion::BBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::BBox >::value();
  }
  static const char* value(const ::fusion::BBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::BBoxRequest> should match
// service_traits::DataType< ::fusion::BBox >
template<>
struct DataType< ::fusion::BBoxRequest>
{
  static const char* value()
  {
    return DataType< ::fusion::BBox >::value();
  }
  static const char* value(const ::fusion::BBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fusion::BBoxResponse> should match
// service_traits::MD5Sum< ::fusion::BBox >
template<>
struct MD5Sum< ::fusion::BBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::BBox >::value();
  }
  static const char* value(const ::fusion::BBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::BBoxResponse> should match
// service_traits::DataType< ::fusion::BBox >
template<>
struct DataType< ::fusion::BBoxResponse>
{
  static const char* value()
  {
    return DataType< ::fusion::BBox >::value();
  }
  static const char* value(const ::fusion::BBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUSION_MESSAGE_BBOX_H
