// Generated by gencpp from file fusion/get_photoResponse.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_GET_PHOTORESPONSE_H
#define FUSION_MESSAGE_GET_PHOTORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fusion
{
template <class ContainerAllocator>
struct get_photoResponse_
{
  typedef get_photoResponse_<ContainerAllocator> Type;

  get_photoResponse_()
    : is_done(false)  {
    }
  get_photoResponse_(const ContainerAllocator& _alloc)
    : is_done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_done_type;
  _is_done_type is_done;





  typedef boost::shared_ptr< ::fusion::get_photoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fusion::get_photoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_photoResponse_

typedef ::fusion::get_photoResponse_<std::allocator<void> > get_photoResponse;

typedef boost::shared_ptr< ::fusion::get_photoResponse > get_photoResponsePtr;
typedef boost::shared_ptr< ::fusion::get_photoResponse const> get_photoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fusion::get_photoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fusion::get_photoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fusion::get_photoResponse_<ContainerAllocator1> & lhs, const ::fusion::get_photoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_done == rhs.is_done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fusion::get_photoResponse_<ContainerAllocator1> & lhs, const ::fusion::get_photoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fusion::get_photoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fusion::get_photoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::get_photoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::get_photoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::get_photoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::get_photoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fusion::get_photoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccf1bf44aca57c0fac7595ea9e4b924c";
  }

  static const char* value(const ::fusion::get_photoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccf1bf44aca57c0fULL;
  static const uint64_t static_value2 = 0xac7595ea9e4b924cULL;
};

template<class ContainerAllocator>
struct DataType< ::fusion::get_photoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fusion/get_photoResponse";
  }

  static const char* value(const ::fusion::get_photoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fusion::get_photoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_done\n"
"\n"
;
  }

  static const char* value(const ::fusion::get_photoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fusion::get_photoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_photoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fusion::get_photoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fusion::get_photoResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSION_MESSAGE_GET_PHOTORESPONSE_H
