// Generated by gencpp from file fusion/get_photo.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_GET_PHOTO_H
#define FUSION_MESSAGE_GET_PHOTO_H

#include <ros/service_traits.h>


#include <fusion/get_photoRequest.h>
#include <fusion/get_photoResponse.h>


namespace fusion
{

struct get_photo
{

typedef get_photoRequest Request;
typedef get_photoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_photo
} // namespace fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fusion::get_photo > {
  static const char* value()
  {
    return "ccf1bf44aca57c0fac7595ea9e4b924c";
  }

  static const char* value(const ::fusion::get_photo&) { return value(); }
};

template<>
struct DataType< ::fusion::get_photo > {
  static const char* value()
  {
    return "fusion/get_photo";
  }

  static const char* value(const ::fusion::get_photo&) { return value(); }
};


// service_traits::MD5Sum< ::fusion::get_photoRequest> should match
// service_traits::MD5Sum< ::fusion::get_photo >
template<>
struct MD5Sum< ::fusion::get_photoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::get_photo >::value();
  }
  static const char* value(const ::fusion::get_photoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::get_photoRequest> should match
// service_traits::DataType< ::fusion::get_photo >
template<>
struct DataType< ::fusion::get_photoRequest>
{
  static const char* value()
  {
    return DataType< ::fusion::get_photo >::value();
  }
  static const char* value(const ::fusion::get_photoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fusion::get_photoResponse> should match
// service_traits::MD5Sum< ::fusion::get_photo >
template<>
struct MD5Sum< ::fusion::get_photoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::get_photo >::value();
  }
  static const char* value(const ::fusion::get_photoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::get_photoResponse> should match
// service_traits::DataType< ::fusion::get_photo >
template<>
struct DataType< ::fusion::get_photoResponse>
{
  static const char* value()
  {
    return DataType< ::fusion::get_photo >::value();
  }
  static const char* value(const ::fusion::get_photoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUSION_MESSAGE_GET_PHOTO_H
