// Generated by gencpp from file fusion/movement.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_MOVEMENT_H
#define FUSION_MESSAGE_MOVEMENT_H

#include <ros/service_traits.h>


#include <fusion/movementRequest.h>
#include <fusion/movementResponse.h>


namespace fusion
{

struct movement
{

typedef movementRequest Request;
typedef movementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct movement
} // namespace fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fusion::movement > {
  static const char* value()
  {
    return "f700a31e1923a44559cb0687bf6c8500";
  }

  static const char* value(const ::fusion::movement&) { return value(); }
};

template<>
struct DataType< ::fusion::movement > {
  static const char* value()
  {
    return "fusion/movement";
  }

  static const char* value(const ::fusion::movement&) { return value(); }
};


// service_traits::MD5Sum< ::fusion::movementRequest> should match
// service_traits::MD5Sum< ::fusion::movement >
template<>
struct MD5Sum< ::fusion::movementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::movement >::value();
  }
  static const char* value(const ::fusion::movementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::movementRequest> should match
// service_traits::DataType< ::fusion::movement >
template<>
struct DataType< ::fusion::movementRequest>
{
  static const char* value()
  {
    return DataType< ::fusion::movement >::value();
  }
  static const char* value(const ::fusion::movementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fusion::movementResponse> should match
// service_traits::MD5Sum< ::fusion::movement >
template<>
struct MD5Sum< ::fusion::movementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::movement >::value();
  }
  static const char* value(const ::fusion::movementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::movementResponse> should match
// service_traits::DataType< ::fusion::movement >
template<>
struct DataType< ::fusion::movementResponse>
{
  static const char* value()
  {
    return DataType< ::fusion::movement >::value();
  }
  static const char* value(const ::fusion::movementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUSION_MESSAGE_MOVEMENT_H
