// Generated by gencpp from file fusion/movementResponse.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_MOVEMENTRESPONSE_H
#define FUSION_MESSAGE_MOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fusion
{
template <class ContainerAllocator>
struct movementResponse_
{
  typedef movementResponse_<ContainerAllocator> Type;

  movementResponse_()
    : radian(0.0)
    , distance(0.0)  {
    }
  movementResponse_(const ContainerAllocator& _alloc)
    : radian(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _radian_type;
  _radian_type radian;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::fusion::movementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fusion::movementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct movementResponse_

typedef ::fusion::movementResponse_<std::allocator<void> > movementResponse;

typedef boost::shared_ptr< ::fusion::movementResponse > movementResponsePtr;
typedef boost::shared_ptr< ::fusion::movementResponse const> movementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fusion::movementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fusion::movementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fusion::movementResponse_<ContainerAllocator1> & lhs, const ::fusion::movementResponse_<ContainerAllocator2> & rhs)
{
  return lhs.radian == rhs.radian &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fusion::movementResponse_<ContainerAllocator1> & lhs, const ::fusion::movementResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fusion::movementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fusion::movementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::movementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::movementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::movementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::movementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fusion::movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d752a56f82b7255790c9bb8872aed2f4";
  }

  static const char* value(const ::fusion::movementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd752a56f82b72557ULL;
  static const uint64_t static_value2 = 0x90c9bb8872aed2f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::fusion::movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fusion/movementResponse";
  }

  static const char* value(const ::fusion::movementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fusion::movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radian\n"
"float64 distance\n"
"\n"
;
  }

  static const char* value(const ::fusion::movementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fusion::movementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radian);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct movementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fusion::movementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fusion::movementResponse_<ContainerAllocator>& v)
  {
    s << indent << "radian: ";
    Printer<double>::stream(s, indent + "  ", v.radian);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSION_MESSAGE_MOVEMENTRESPONSE_H
