// Generated by gencpp from file fusion/nav_resultResponse.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_NAV_RESULTRESPONSE_H
#define FUSION_MESSAGE_NAV_RESULTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fusion
{
template <class ContainerAllocator>
struct nav_resultResponse_
{
  typedef nav_resultResponse_<ContainerAllocator> Type;

  nav_resultResponse_()
    : isget(false)  {
    }
  nav_resultResponse_(const ContainerAllocator& _alloc)
    : isget(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isget_type;
  _isget_type isget;





  typedef boost::shared_ptr< ::fusion::nav_resultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fusion::nav_resultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nav_resultResponse_

typedef ::fusion::nav_resultResponse_<std::allocator<void> > nav_resultResponse;

typedef boost::shared_ptr< ::fusion::nav_resultResponse > nav_resultResponsePtr;
typedef boost::shared_ptr< ::fusion::nav_resultResponse const> nav_resultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fusion::nav_resultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fusion::nav_resultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fusion::nav_resultResponse_<ContainerAllocator1> & lhs, const ::fusion::nav_resultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isget == rhs.isget;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fusion::nav_resultResponse_<ContainerAllocator1> & lhs, const ::fusion::nav_resultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fusion::nav_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fusion::nav_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::nav_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::nav_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::nav_resultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::nav_resultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fusion::nav_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bda93c4597d4f36521d8edb72019720";
  }

  static const char* value(const ::fusion::nav_resultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bda93c4597d4f36ULL;
  static const uint64_t static_value2 = 0x521d8edb72019720ULL;
};

template<class ContainerAllocator>
struct DataType< ::fusion::nav_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fusion/nav_resultResponse";
  }

  static const char* value(const ::fusion::nav_resultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fusion::nav_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isget\n"
"\n"
;
  }

  static const char* value(const ::fusion::nav_resultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fusion::nav_resultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isget);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_resultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fusion::nav_resultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fusion::nav_resultResponse_<ContainerAllocator>& v)
  {
    s << indent << "isget: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isget);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSION_MESSAGE_NAV_RESULTRESPONSE_H
