// Generated by gencpp from file fusion/yolo_modelRequest.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_YOLO_MODELREQUEST_H
#define FUSION_MESSAGE_YOLO_MODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fusion
{
template <class ContainerAllocator>
struct yolo_modelRequest_
{
  typedef yolo_modelRequest_<ContainerAllocator> Type;

  yolo_modelRequest_()
    {
    }
  yolo_modelRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fusion::yolo_modelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fusion::yolo_modelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct yolo_modelRequest_

typedef ::fusion::yolo_modelRequest_<std::allocator<void> > yolo_modelRequest;

typedef boost::shared_ptr< ::fusion::yolo_modelRequest > yolo_modelRequestPtr;
typedef boost::shared_ptr< ::fusion::yolo_modelRequest const> yolo_modelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fusion::yolo_modelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fusion::yolo_modelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fusion::yolo_modelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fusion::yolo_modelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::yolo_modelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fusion::yolo_modelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::yolo_modelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fusion::yolo_modelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fusion::yolo_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fusion::yolo_modelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fusion::yolo_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fusion/yolo_modelRequest";
  }

  static const char* value(const ::fusion::yolo_modelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fusion::yolo_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::fusion::yolo_modelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fusion::yolo_modelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolo_modelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fusion::yolo_modelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fusion::yolo_modelRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FUSION_MESSAGE_YOLO_MODELREQUEST_H
