// Generated by gencpp from file fusion/yolo_model.msg
// DO NOT EDIT!


#ifndef FUSION_MESSAGE_YOLO_MODEL_H
#define FUSION_MESSAGE_YOLO_MODEL_H

#include <ros/service_traits.h>


#include <fusion/yolo_modelRequest.h>
#include <fusion/yolo_modelResponse.h>


namespace fusion
{

struct yolo_model
{

typedef yolo_modelRequest Request;
typedef yolo_modelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yolo_model
} // namespace fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fusion::yolo_model > {
  static const char* value()
  {
    return "413fba5d33e359512198fd983aafb45c";
  }

  static const char* value(const ::fusion::yolo_model&) { return value(); }
};

template<>
struct DataType< ::fusion::yolo_model > {
  static const char* value()
  {
    return "fusion/yolo_model";
  }

  static const char* value(const ::fusion::yolo_model&) { return value(); }
};


// service_traits::MD5Sum< ::fusion::yolo_modelRequest> should match
// service_traits::MD5Sum< ::fusion::yolo_model >
template<>
struct MD5Sum< ::fusion::yolo_modelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::yolo_model >::value();
  }
  static const char* value(const ::fusion::yolo_modelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::yolo_modelRequest> should match
// service_traits::DataType< ::fusion::yolo_model >
template<>
struct DataType< ::fusion::yolo_modelRequest>
{
  static const char* value()
  {
    return DataType< ::fusion::yolo_model >::value();
  }
  static const char* value(const ::fusion::yolo_modelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fusion::yolo_modelResponse> should match
// service_traits::MD5Sum< ::fusion::yolo_model >
template<>
struct MD5Sum< ::fusion::yolo_modelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fusion::yolo_model >::value();
  }
  static const char* value(const ::fusion::yolo_modelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fusion::yolo_modelResponse> should match
// service_traits::DataType< ::fusion::yolo_model >
template<>
struct DataType< ::fusion::yolo_modelResponse>
{
  static const char* value()
  {
    return DataType< ::fusion::yolo_model >::value();
  }
  static const char* value(const ::fusion::yolo_modelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUSION_MESSAGE_YOLO_MODEL_H
