<robot name = "mycar" xmlns:xacro = "http://www.ros.org/wiki/xacro">
    <xacro:property name = "camera_length" value = "0.01"/>
    <xacro:property name = "camera_width" value = "0.025"/>
    <xacro:property name = "camera_height" value = "0.025"/>
    <xacro:property name = "camera_mass" value = "0.01"/>
    <xacro:property name = "joint_camera_x" value = "0.08"/>
    <xacro:property name = "joint_camera_y" value = "0"/>
    <xacro:property name = "joint_camera_z" value = "${base_length / 2 + camera_height / 2}"/>

    <link name = "camera"> 
        <visual>
            <geometry>
                <box size = "${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name = "black">
                <color rgba = "0 0 0 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size = "${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m = "${camera_mass}" l = "${camera_length}" w = "${camera_width}" h = "${camera_height}"/>
    </link>
    <gazebo reference = "camera">
        <material>Gazebo/Blue</material>
    </gazebo>
    <joint name = "camera2base" type = "fixed">
        <parent link = "base_link"/>
        <child link = "camera"/>
        <origin xyz = "${joint_camera_x} ${joint_camera_y} ${joint_camera_z}"/>
    </joint>
</robot>
